# Generated by Django 3.2.8 on 2021-12-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bets', '0003_bet_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='team',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
