# Generated by Django 3.2.8 on 2021-12-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bets', '0004_bet_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='game_id',
            field=models.CharField(max_length=200),
        ),
    ]
